# Generated by Django 5.0 on 2023-12-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Project Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Project Description"
                    ),
                ),
                (
                    "file_upload",
                    models.ImageField(
                        default="media/pages/default.jpg", upload_to="project_images/"
                    ),
                ),
            ],
        ),
    ]
