# Generated by Django 5.0 on 2023-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="slug",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Projects Link"
            ),
        ),
    ]
