# Generated by Django 5.0 on 2023-12-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_projects_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="file_upload",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
    ]
