# Generated by Django 5.0 on 2023-12-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_projects_file_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Category Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tagName",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="Programming Language Name",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projects",
            name="url",
            field=models.URLField(null=True, verbose_name="Project URL Link"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Projects Slug"
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pages.category",
                verbose_name="Project Category",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="tags",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pages.tag",
                verbose_name="Project Programming Language",
            ),
        ),
    ]
