# Generated by Django 5.0 on 2023-12-09 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_category_tag_projects_url_alter_projects_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="url",
            new_name="project_url",
        ),
    ]
